// Base URL for the `kalama` audio assets (words, names, sfx).
// Defaults to the remote GitHub mirror used by the website. For the Android/app
// build, set PUBLIC_KALAMA_BASE to a bundled local path so audio works offline.
export const KALAMA =
  import.meta.env.PUBLIC_KALAMA_BASE ??
  "https://raw.githubusercontent.com/wasona/kalama/main";

export const ipaRecordings: Record<string, string> = {
  m: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Bilabial_nasal.ogg",
  ɱ: "https://upload.wikimedia.org/wikipedia/commons/1/18/Labiodental_nasal.ogg",
  n: "https://upload.wikimedia.org/wikipedia/commons/2/29/Alveolar_nasal.ogg",
  ɳ: "https://upload.wikimedia.org/wikipedia/commons/a/af/Retroflex_nasal.ogg",
  ɲ: "https://upload.wikimedia.org/wikipedia/commons/4/46/Palatal_nasal.ogg",
  ŋ: "https://upload.wikimedia.org/wikipedia/commons/3/39/Velar_nasal.ogg",
  ɴ: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Uvular_nasal.ogg",
  p: "https://upload.wikimedia.org/wikipedia/commons/5/51/Voiceless_bilabial_plosive.ogg",
  b: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Voiced_bilabial_plosive.ogg",
  t̼: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Voiceless_linguolabial_stop.ogg",
  d̼: "https://upload.wikimedia.org/wikipedia/commons/9/95/Voiced_linguolabial_stop.ogg",
  t̪: "https://upload.wikimedia.org/wikipedia/commons/d/dc/Voiceless_dental_stop.ogg",
  d̪: "https://upload.wikimedia.org/wikipedia/commons/1/1c/Voiced_dental_stop.ogg",
  t: "https://upload.wikimedia.org/wikipedia/commons/0/02/Voiceless_alveolar_plosive.ogg",
  d: "https://upload.wikimedia.org/wikipedia/commons/0/01/Voiced_alveolar_plosive.ogg",
  ʈ: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Voiceless_retroflex_stop.oga",
  ɖ: "https://upload.wikimedia.org/wikipedia/commons/2/27/Voiced_retroflex_stop.oga",
  c: "https://upload.wikimedia.org/wikipedia/commons/5/5d/Voiceless_palatal_plosive.ogg",
  ɟ: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Voiced_palatal_plosive.ogg",
  k: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Voiceless_velar_plosive.ogg",
  g: "https://upload.wikimedia.org/wikipedia/commons/1/12/Voiced_velar_plosive_02.ogg",
  q: "https://upload.wikimedia.org/wikipedia/commons/1/19/Voiceless_uvular_plosive.ogg",
  ɢ: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Voiced_uvular_stop.oga",
  ʡ: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Epiglottal_stop.ogg",
  ʔ: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Glottal_stop.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/b/b5/Voiceless_dental_sibilant_affricate.oga",
  // :  "https://upload.wikimedia.org/wikipedia/commons/1/16/Voiced_dental_sibilant_affricate.oga",
  ts: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Voiceless_alveolar_sibilant_affricate.oga",
  dz: "https://upload.wikimedia.org/wikipedia/commons/d/d8/Voiced_alveolar_sibilant_affricate.oga",
  tʃ: "https://upload.wikimedia.org/wikipedia/commons/9/97/Voiceless_palato-alveolar_affricate.ogg",
  dʒ: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Voiced_palato-alveolar_affricate.ogg",
  tʂ: "https://upload.wikimedia.org/wikipedia/commons/e/e9/Voiceless_retroflex_affricate.ogg",
  dʐ: "https://upload.wikimedia.org/wikipedia/commons/5/58/Voiced_retroflex_affricate.ogg",
  tɕ: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Voiceless_alveolo-palatal_affricate.ogg",
  dʑ: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Voiced_alveolo-palatal_affricate.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/4/4a/Voiceless_bilabial_affricate.ogg",
  pf: "https://upload.wikimedia.org/wikipedia/commons/8/83/Voiceless_labiodental_affricate.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/3/33/Voiced_labiodental_affricate.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/2/27/Voiced_dental_non-sibilant_affricate.oga",
  // :  "https://upload.wikimedia.org/wikipedia/commons/2/27/Voiced_dental_non-sibilant_affricate.oga",
  // :  "https://upload.wikimedia.org/wikipedia/commons/f/f4/Voiceless_postalveolar_non-sibilant_affricate.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/d/d7/Voiced_postalveolar_non-sibilant_affricate.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/f/fd/Voiceless_palatal_affricate.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/a/aa/Voiced_palatal_affricate.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/e/e5/Voiceless_velar_affricate.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/7/75/Voiced_velar_affricate.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/4/43/Voiceless_uvular_affricate.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/3/35/Voiced_uvular_affricate.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/e/ea/Voiceless_epiglottal_affricate.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/e/e4/Voiced_epiglottal_affricate.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/4/44/Voiceless_glottal_affricate.ogg",
  s: "https://upload.wikimedia.org/wikipedia/commons/a/ac/Voiceless_alveolar_sibilant.ogg",
  z: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Voiced_alveolar_sibilant.ogg",
  ʃ: "https://upload.wikimedia.org/wikipedia/commons/c/cc/Voiceless_palato-alveolar_sibilant.ogg",
  ʒ: "https://upload.wikimedia.org/wikipedia/commons/3/30/Voiced_palato-alveolar_sibilant.ogg",
  ʂ: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Voiceless_retroflex_sibilant.ogg",
  ʐ: "https://upload.wikimedia.org/wikipedia/commons/7/7f/Voiced_retroflex_sibilant.ogg",
  ɕ: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Voiceless_alveolo-palatal_sibilant.ogg",
  ʑ: "https://upload.wikimedia.org/wikipedia/commons/1/15/Voiced_alveolo-palatal_sibilant.ogg",
  ɸ: "https://upload.wikimedia.org/wikipedia/commons/4/41/Voiceless_bilabial_fricative.ogg",
  β: "https://upload.wikimedia.org/wikipedia/commons/3/37/Voiced_bilabial_fricative.ogg",
  f: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Voiceless_labio-dental_fricative.ogg",
  v: "https://upload.wikimedia.org/wikipedia/commons/4/42/Voiced_labio-dental_fricative.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/a/a0/Voiceless_linguolabial_fricative.ogg",
  θ: "https://upload.wikimedia.org/wikipedia/commons/8/80/Voiceless_dental_fricative.ogg",
  ð: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Voiced_dental_fricative.ogg",
  // : "https://upload.wikimedia.org/wikipedia/commons/a/aa/Voiceless_alveolar_non-sibilant_fricative.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/0/0a/Voiced_alveolar_non-sibilant_fricative.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/a/ab/Voiceless_postalveolar_non-sibilant_fricative.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/0/0a/Voiced_postalveolar_non-sibilant_fricative.ogg",
  ç: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Voiceless_palatal_fricative.ogg",
  ʝ: "https://upload.wikimedia.org/wikipedia/commons/a/ac/Voiced_palatal_fricative.ogg",
  x: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Voiceless_velar_fricative.ogg",
  ɣ: "https://upload.wikimedia.org/wikipedia/commons/4/47/Voiced_velar_fricative.ogg",
  χ: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Voiceless_uvular_fricative.ogg",
  ʁ: "https://upload.wikimedia.org/wikipedia/commons/a/af/Voiced_uvular_fricative.ogg",
  ħ: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Voiceless_pharyngeal_fricative.ogg",
  ʕ: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Voiced_pharyngeal_fricative.ogg",
  h: "https://upload.wikimedia.org/wikipedia/commons/d/da/Voiceless_glottal_fricative.ogg",
  ɦ: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Voiced_glottal_fricative.ogg",
  w: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Voiced_labio-velar_approximant.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/1/11/Bilabial_approximant.ogg",
  ʋ: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Labiodental_approximant.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/1/11/Voiced_dental_approximant.ogg",
  ɹ: "https://upload.wikimedia.org/wikipedia/commons/1/1f/Alveolar_approximant.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/3/33/Postalveolar_approximant.ogg",
  ɻ: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Retroflex_Approximant2.oga",
  ɻʷ: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Retroflex_approximant.ogg",
  j: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Palatal_approximant.ogg",
  ɰ: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Voiced_velar_approximant.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/1/19/Voiced_Uvular_Approximant.ogg",
  ⱱ: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Labiodental_flap.ogg",
  ɾ: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Alveolar_tap.ogg",
  ɽ: "https://upload.wikimedia.org/wikipedia/commons/8/87/Retroflex_flap.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/f/f1/Epiglottal_flap.oga",
  // :  "https://upload.wikimedia.org/wikipedia/commons/e/ec/Voiceless_bilabial_trill_with_aspiration.ogg",
  ʙ: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Bilabial_trill.ogg",
  r̥: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Voiceless_alveolar_trill.ogg",
  r: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Alveolar_trill.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/a/ae/Voiced_postalveolar_trill.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/2/29/Voiced_retroflex_trill.ogg",
  ʀ̥: "https://upload.wikimedia.org/wikipedia/commons/8/8d/Voiceless_uvular_trill.ogg",
  ʀ: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Uvular_trill.ogg",
  ʜ: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Voiceless_epiglottal_trill.ogg",
  ʢ: "https://upload.wikimedia.org/wikipedia/commons/1/18/Voiced_epiglottal_trill_2.ogg",
  tɬ: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Voiceless_alveolar_lateral_affricate.ogg",
  dɮ: "https://upload.wikimedia.org/wikipedia/commons/3/31/Voiced_alveolar_lateral_affricate.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/c/ce/Voiceless_palatal_lateral_affricate.ogg",
  // :  "hhttps://upload.wikimedia.org/wikipedia/commons/0/02/Voiceless_velar_lateral_affricate.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/9/93/Voiced_velar_lateral_affricate.ogg",
  ɬ: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Voiceless_alveolar_lateral_fricative.ogg",
  ɮ: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Voiced_alveolar_lateral_fricative.ogg",
  ꞎ: "https://upload.wikimedia.org/wikipedia/commons/5/54/Voiceless_retroflex_lateral_fricative.ogg",
  𝼆: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Voiceless_palatal_lateral_fricative.ogg",
  𝼄: "https://upload.wikimedia.org/wikipedia/commons/9/99/Voiceless_velar_lateral_fricative.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/2/24/Voiced_velar_lateral_fricative.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/f/f8/Voiced_dental_lateral_approximant.ogg",
  l: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Alveolar_lateral_approximant.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/5/5b/Voiced_postalveolar_lateral_approximant.ogg",
  ɭ: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Retroflex_lateral_approximant.ogg",
  ʎ: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Palatal_lateral_approximant.ogg",
  ʟ: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Velar_lateral_approximant.ogg",
  // :  "https://upload.wikimedia.org/wikipedia/commons/7/73/Uvular_lateral_approximant.ogg",

  ŋwiəŋ:
    "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/16/Nguyen.ogg/Nguyen.ogg.mp3",
};
