// UCSUR, as of 2025.
// Includes 137 nimi pu + nimi ku suli,
// plus majuna, apeja, pake, powe.
const dictionary: Record<string, string> = {
  a: "󱤀",
  akesi: "󱤁",
  ala: "󱤂",
  alasa: "󱤃",
  ale: "󱤄",
  anpa: "󱤅",
  ante: "󱤆",
  anu: "󱤇",
  apeja: "󱦡",
  awen: "󱤈",
  e: "󱤉",
  en: "󱤊",
  epiku: "󱦃",
  esun: "󱤋",
  ijo: "󱤌",
  ike: "󱤍",
  ilo: "󱤎",
  insa: "󱤏",
  jaki: "󱤐",
  jan: "󱤑",
  jasima: "󱥿",
  jelo: "󱤒",
  jo: "󱤓",
  kala: "󱤔",
  kalama: "󱤕",
  kama: "󱤖",
  kasi: "󱤗",
  ken: "󱤘",
  kepeken: "󱤙",
  kijetesantakalu: "󱦀",
  kili: "󱤚",
  kin: "󱥹",
  kipisi: "󱥻",
  kiwen: "󱤛",
  ko: "󱤜",
  kokosila: "󱦄",
  kon: "󱤝",
  ku: "󱦈",
  kule: "󱤞",
  kulupu: "󱤟",
  kute: "󱤠",
  la: "󱤡",
  lanpan: "󱦅",
  lape: "󱤢",
  laso: "󱤣",
  lawa: "󱤤",
  leko: "󱥼",
  len: "󱤥",
  lete: "󱤦",
  li: "󱤧",
  lili: "󱤨",
  linja: "󱤩",
  lipu: "󱤪",
  loje: "󱤫",
  lon: "󱤬",
  luka: "󱤭",
  lukin: "󱤮",
  lupa: "󱤯",
  ma: "󱤰",
  majuna: "󱦢",
  mama: "󱤱",
  mani: "󱤲",
  meli: "󱤳",
  meso: "󱦂",
  mi: "󱤴",
  mije: "󱤵",
  misikeke: "󱦇",
  moku: "󱤶",
  moli: "󱤷",
  monsi: "󱤸",
  monsuta: "󱥽",
  mu: "󱤹",
  mun: "󱤺",
  musi: "󱤻",
  mute: "󱤼",
  n: "󱦆",
  namako: "󱥸",
  nanpa: "󱤽",
  nasa: "󱤾",
  nasin: "󱤿",
  nena: "󱥀",
  ni: "󱥁",
  nimi: "󱥂",
  noka: "󱥃",
  o: "󱥄",
  oko: "󱥺",
  olin: "󱥅",
  ona: "󱥆",
  open: "󱥇",
  pakala: "󱥈",
  pake: "󱦠",
  pali: "󱥉",
  palisa: "󱥊",
  pan: "󱥋",
  pana: "󱥌",
  pi: "󱥍",
  pilin: "󱥎",
  pimeja: "󱥏",
  pini: "󱥐",
  pipi: "󱥑",
  poka: "󱥒",
  poki: "󱥓",
  pona: "󱥔",
  powe: "󱦣",
  pu: "󱥕",
  sama: "󱥖",
  seli: "󱥗",
  selo: "󱥘",
  seme: "󱥙",
  sewi: "󱥚",
  sijelo: "󱥛",
  sike: "󱥜",
  sin: "󱥝",
  sina: "󱥞",
  sinpin: "󱥟",
  sitelen: "󱥠",
  soko: "󱦁",
  sona: "󱥡",
  soweli: "󱥢",
  suli: "󱥣",
  suno: "󱥤",
  supa: "󱥥",
  suwi: "󱥦",
  tan: "󱥧",
  taso: "󱥨",
  tawa: "󱥩",
  telo: "󱥪",
  tenpo: "󱥫",
  toki: "󱥬",
  tomo: "󱥭",
  tonsi: "󱥾",
  tu: "󱥮",
  unpa: "󱥯",
  uta: "󱥰",
  utala: "󱥱",
  walo: "󱥲",
  wan: "󱥳",
  waso: "󱥴",
  wawa: "󱥵",
  weka: "󱥶",
  wile: "󱥷",
};

// Obviously in real use, there is no "sitelen pona alphabet";
// This is a cheap trick to weigh cartouches in favour of words
// that I teach early.
const alphabet: Record<string, string> = {
  m: "󱤶",
  n: "󱥁",
  p: "󱥔",
  t: "󱥬",
  k: "󱤗",
  s: "󱥡",
  w: "󱥴",
  l: "󱤧",
  j: "󱤑",
  a: "󱤂",
  e: "󱤉",
  i: "󱤍",
  o: "󱥆",
  u: "󱥱",
};

function encodeName(word: string) {
  return [
    "󱦐",
    ...word
      .toLowerCase()
      .split("")
      .map((letter: string) => alphabet[letter]),
    "󱦑",
  ].join("");
}

export function encode(text: string) {
  return text
    .replaceAll(/[\.\!\?]/g, "")
    .split(" ")
    .map((word) => (word in dictionary ? dictionary[word] : encodeName(word)))
    .join("");
}
